services:
  # Backend web service
  - type: web
    name: newsletter-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: NEWSAPI_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: newsletter-db
          property: connectionString

databases:
  - name: newsletter-db
    databaseName: newsletter
    user: newsletter_user
