services:
  - type: web
    name: newsletter-frontend
    env: static
    buildCommand: |
      export SHELL=/bin/bash
      npm install -g pnpm
      pnpm install
      pnpm build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.12.0
